/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BACKEND.managers.AppManager;
import BACKEND.managers.GoalManager;
import BACKEND.managers.UserManager;
import java.awt.Dialog;
import java.io.IOException;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.Temporal;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;

/**
 *
 * @author Kyrab
 */
public class GoalSection extends javax.swing.JFrame {

    /**
     * Creates new form GoalSection
     */
    private String generatedPlanStr;

    public GoalSection() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        currentGoalsHeadingLbl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        helpLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        specificGoalTxt = new javax.swing.JTextField();
        typeOfGoalComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersInputTxt = new javax.swing.JTextArea();
        generatePlanBttn = new javax.swing.JButton();
        startDatePicker = new com.toedter.calendar.JDateChooser();
        endDatePicker = new com.toedter.calendar.JDateChooser();
        addGoalToCalBttn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        generatedPlanBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(78, 81, 140));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(44, 42, 74));

        currentGoalsHeadingLbl1.setBackground(new java.awt.Color(102, 255, 255));
        currentGoalsHeadingLbl1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        currentGoalsHeadingLbl1.setForeground(new java.awt.Color(153, 255, 255));
        currentGoalsHeadingLbl1.setText("Goals");

        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("<Home");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        helpLbl.setForeground(new java.awt.Color(255, 255, 255));
        helpLbl.setText("Help");
        helpLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(181, 229, 237)));
        helpLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(currentGoalsHeadingLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(helpLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentGoalsHeadingLbl1)
                    .addComponent(jLabel1)
                    .addComponent(helpLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Type of Goal:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, 112, -1));

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Starting date: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("Deadline:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Specify Goal:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        specificGoalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificGoalTxtActionPerformed(evt);
            }
        });
        jPanel1.add(specificGoalTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 30));

        typeOfGoalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personal goal", "Academic goal", "Social goal", "Physical goal" }));
        jPanel1.add(typeOfGoalComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Extra Information:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 150, 20));

        usersInputTxt.setColumns(20);
        usersInputTxt.setRows(5);
        jScrollPane1.setViewportView(usersInputTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 180));

        generatePlanBttn.setText("Generate your plan");
        generatePlanBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePlanBttnActionPerformed(evt);
            }
        });
        jPanel1.add(generatePlanBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel1.add(startDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 200, 30));
        jPanel1.add(endDatePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 200, 30));

        addGoalToCalBttn.setText("Add goal to calendar");
        addGoalToCalBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGoalToCalBttnActionPerformed(evt);
            }
        });
        jPanel1.add(addGoalToCalBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 170, -1));

        jLabel7.setText("Your plan:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, 20));

        generatedPlanBox.setBackground(new java.awt.Color(153, 153, 255));
        generatedPlanBox.setColumns(20);
        generatedPlanBox.setForeground(new java.awt.Color(44, 42, 74));
        generatedPlanBox.setRows(5);
        jScrollPane2.setViewportView(generatedPlanBox);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 270, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        dispose();
        try {
            new HomeScreen().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(GoalSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void specificGoalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificGoalTxtActionPerformed

    }//GEN-LAST:event_specificGoalTxtActionPerformed

    private void addGoalToCalBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGoalToCalBttnActionPerformed
        JFrame error = new JFrame();
        String typeOfGoal = (String) typeOfGoalComboBox.getSelectedItem();
        String specificGoal = specificGoalTxt.getText();
        java.util.Date startDate = startDatePicker.getDate();
        java.util.Date endDate = endDatePicker.getDate();
        LocalDate goalStartDate = startDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate goalEndDate = endDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String getGeneratedPlan = generatedPlanBox.getText();
        int userId = AppManager.userManager.getCurrentUserID();
        int stepsCompleted = 0;
        try {
            AppManager.goalManager.addGoal(userId, typeOfGoal, specificGoal, getGeneratedPlan, goalStartDate, goalEndDate, stepsCompleted);
            if (startDatePicker.getDate() == null || endDatePicker.getDate() == null) {
                JOptionPane.showMessageDialog(error, "please eneter start and end dates ");

            }
            JOptionPane.showMessageDialog(error, "successfully added");
        } catch (SQLException ex) {
            Logger.getLogger(GoalSection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(error, "plan need to be shortened");
        }


    }//GEN-LAST:event_addGoalToCalBttnActionPerformed

    private void generatePlanBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePlanBttnActionPerformed

        String usersInput = this.usersInputTxt.getText();
        String usersSpecificGoal = specificGoalTxt.getText();
        JDialog loadingDialog = new JDialog(this, "Loading", Dialog.ModalityType.APPLICATION_MODAL);
        JLabel loadingLabel = new JLabel("Loading...", SwingConstants.CENTER);
        loadingDialog.add(loadingLabel);
        loadingDialog.setSize(200, 100);
        loadingDialog.setLocationRelativeTo(this);
        SwingWorker<String, Void> worker = new SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                try {
                    String usersInput = usersInputTxt.getText();
                    String encodedGoal = URLEncoder.encode(specificGoalTxt.getText(), StandardCharsets.UTF_8);
                    String encodedUserInput = URLEncoder.encode(usersInput, StandardCharsets.UTF_8);
                    String request = "Make a step by step plan that will allow me to complete my goal of " + encodedGoal + ". please incorporate this extra information:" + encodedUserInput + " return your response in numbered points  and restrict response to less than 2000 words.";
                    String response = AppManager.bot.askChatBot(request);
                    return response.replace("'", "''");
                } catch (IOException ex) {
                    Logger.getLogger(GoalSection.class.getName()).log(Level.SEVERE, null, ex);
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    generatedPlanStr = get();
                    if (generatedPlanStr != null) {
                        generatedPlanBox.setText(generatedPlanStr);
                    }
                } catch (InterruptedException | ExecutionException e) {
                    e.printStackTrace();
                } finally {
                    loadingDialog.dispose(); 
                }
            }
        };
        worker.execute();
        loadingDialog.setVisible(true); 

    }//GEN-LAST:event_generatePlanBttnActionPerformed

    private void helpLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpLblMousePressed
        JFrame helpMenu = new JFrame();
        JOptionPane.showMessageDialog(helpMenu, "In order for a goal to be added all fields must be filled. \n Your generated plan will take a few seconds.\n Once your plan is generated you can edit it in the box to fit your needs.");
    }//GEN-LAST:event_helpLblMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GoalSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GoalSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GoalSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GoalSection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GoalSection().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGoalToCalBttn;
    private javax.swing.JLabel currentGoalsHeadingLbl1;
    private com.toedter.calendar.JDateChooser endDatePicker;
    private javax.swing.JButton generatePlanBttn;
    private javax.swing.JTextArea generatedPlanBox;
    private javax.swing.JLabel helpLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField specificGoalTxt;
    private com.toedter.calendar.JDateChooser startDatePicker;
    private javax.swing.JComboBox<String> typeOfGoalComboBox;
    private javax.swing.JTextArea usersInputTxt;
    // End of variables declaration//GEN-END:variables
}
