/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import BACKEND.EntryValidator;
import BACKEND.managers.AppManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyrab
 */
public class LogInScreen extends javax.swing.JFrame {

    /**
     * Creates new form LogInScreena
     */
  
    
    private EntryValidator v;
    private boolean usernameValidator = true;
    private boolean passwordValidator = true;

    public LogInScreen() throws ClassNotFoundException, SQLException {
        initComponents();
      
        v = new EntryValidator();
        AppManager.init();
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordTxtField = new javax.swing.JTextField();
        usernameTxtField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logInBttn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        usernameErrorLbl = new javax.swing.JLabel();
        passwordErrorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 42, 74));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTxtField.setForeground(new java.awt.Color(78, 81, 140));
        passwordTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtFieldActionPerformed(evt);
            }
        });
        passwordTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtFieldKeyReleased(evt);
            }
        });
        jPanel1.add(passwordTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 210, 40));

        usernameTxtField.setForeground(new java.awt.Color(78, 81, 140));
        usernameTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameTxtFieldKeyReleased(evt);
            }
        });
        jPanel1.add(usernameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 210, 40));

        jPanel2.setBackground(new java.awt.Color(78, 81, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/c28b72a832bb4eacae54d8ca39fa12cf.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (3) (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, 80));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, -1));

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 60, -1));

        logInBttn.setText("Log In");
        logInBttn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        logInBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInBttnActionPerformed(evt);
            }
        });
        jPanel1.add(logInBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 100, 30));

        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Sign Up here");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 90, 20));

        usernameErrorLbl.setBackground(new java.awt.Color(153, 255, 255));
        usernameErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(usernameErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 210, 30));

        passwordErrorLbl.setBackground(new java.awt.Color(153, 255, 255));
        passwordErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(passwordErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtFieldActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        dispose();
        new SignUpScreen().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void logInBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInBttnActionPerformed
        String username = usernameTxtField.getText();
        String password = passwordTxtField.getText();
        if (usernameValidator && passwordValidator) {
            if (AppManager.userManager.checkUser(username, password)) {
                dispose();
                try {
                    new HomeScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LogInScreen.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "username or password is insorrect");
            }
        } else {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "password or username format is incorrect");
        }
    }//GEN-LAST:event_logInBttnActionPerformed

    private void usernameTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameTxtFieldKeyReleased
        String username = usernameTxtField.getText();
        if (!v.PresenceCheck(username)) {
            usernameErrorLbl.setText("name is required");
            usernameValidator = false;
        } else {

            usernameErrorLbl.setText(" ");
            usernameValidator = true;
        }
    }//GEN-LAST:event_usernameTxtFieldKeyReleased

    private void passwordTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtFieldKeyReleased
        String password = passwordTxtField.getText();
        if (!v.PresenceCheck(password)) {
            passwordErrorLbl.setText("password is required");
            passwordValidator = false;
        } else {

            passwordErrorLbl.setText(" ");
            passwordValidator = true;
        }
    }//GEN-LAST:event_passwordTxtFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LogInScreen().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LogInScreen.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LogInScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logInBttn;
    private javax.swing.JLabel passwordErrorLbl;
    private javax.swing.JTextField passwordTxtField;
    private javax.swing.JLabel usernameErrorLbl;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables
}
