/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BACKEND.EntryValidator;
import BACKEND.managers.AppManager;
import BACKEND.managers.UserManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Kyra Balliram
 */
public class SignUpScreen extends javax.swing.JFrame {

    /**
     * Creates new form SignUPScreen
     */
    private EntryValidator v;
    private boolean firstNameValidator = true;
    private boolean lastNameValidator = true;
    private boolean usernameValidator = true;
    private boolean passwordValidator = true;

    public SignUpScreen() {
        initComponents();

        v = new EntryValidator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        signUpBttn = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordErrorLbl = new javax.swing.JLabel();
        firstNameErrorLbl = new javax.swing.JLabel();
        lastNameErrorLbl = new javax.swing.JLabel();
        usernameErrorLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(514, 550));

        jPanel1.setBackground(new java.awt.Color(44, 42, 74));
        jPanel1.setMinimumSize(new java.awt.Dimension(514, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordField.setForeground(new java.awt.Color(78, 81, 140));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 210, 30));

        usernameField.setForeground(new java.awt.Color(78, 81, 140));
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 210, 30));

        jPanel2.setBackground(new java.awt.Color(78, 81, 140));
        jPanel2.setForeground(new java.awt.Color(78, 81, 140));
        jPanel2.setToolTipText("");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/c28b72a832bb4eacae54d8ca39fa12cf.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("<Log In Screen");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(172, 172, 172)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (3) (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 80));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 90, -1));

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 60, -1));

        signUpBttn.setText("Sign Up");
        signUpBttn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));
        signUpBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBttnActionPerformed(evt);
            }
        });
        jPanel1.add(signUpBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 110, 30));

        firstNameField.setForeground(new java.awt.Color(78, 81, 140));
        firstNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                firstNameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, 30));

        lastNameField.setForeground(new java.awt.Color(78, 81, 140));
        lastNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastNameFieldKeyReleased(evt);
            }
        });
        jPanel1.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 210, 30));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Surname:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 90, -1));

        passwordErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(passwordErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 210, 30));

        firstNameErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(firstNameErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 210, 30));

        lastNameErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(lastNameErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 210, 30));

        usernameErrorLbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(usernameErrorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 210, 30));

        jLabel8.setBackground(new java.awt.Color(153, 255, 255));
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void signUpBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBttnActionPerformed
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String username = usernameField.getText();
        String password = passwordField.getText();
    
        if (firstNameValidator && lastNameValidator && usernameValidator && passwordValidator) {
            try {
                AppManager.userManager.addUser(firstName, lastName, username, password);
                dispose();
                new HomeScreen().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(SignUpScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Incorrect format of fields");
        }
    }//GEN-LAST:event_signUpBttnActionPerformed

    private void firstNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameFieldKeyReleased
        String firstName = firstNameField.getText();
        if (!v.PresenceCheck(firstName)) {
            firstNameErrorLbl.setText("name is required");
            firstNameValidator = false;
        } else if (!v.checkForLetters(firstName)) {
            firstNameErrorLbl.setText("name cannot contain numbers");
            firstNameValidator = false;
        } else {
            firstNameErrorLbl.setText(" ");
            firstNameValidator = true;
        }
    }//GEN-LAST:event_firstNameFieldKeyReleased

    private void lastNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastNameFieldKeyReleased
        String lastName = lastNameField.getText();
        if (!v.PresenceCheck(lastName)) {
            lastNameErrorLbl.setText("name is required");
            lastNameValidator = false;
        } else if (!v.checkForLetters(lastName)) {
            lastNameErrorLbl.setText("name cannot contain numbers");
            lastNameValidator = false;
        } else {
            lastNameErrorLbl.setText(" ");
            lastNameValidator = true;
        }
    }//GEN-LAST:event_lastNameFieldKeyReleased

    private void usernameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldKeyReleased
        String username = usernameField.getText();
        if (!v.PresenceCheck(username)) {
            usernameErrorLbl.setText("name is required");
            usernameValidator = false;
        } else {
            usernameErrorLbl.setText(" ");
            usernameValidator = true;
        }
    }//GEN-LAST:event_usernameFieldKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        String password = passwordField.getText();
        if (!v.PresenceCheck(password)) {
            passwordErrorLbl.setText("password is required");
            passwordValidator = false;
        } else {

            passwordErrorLbl.setText(" ");
            passwordValidator = true;
        }
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        dispose();
        try {
            new LogInScreen().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUpScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SignUpScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameErrorLbl;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameErrorLbl;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel passwordErrorLbl;
    private javax.swing.JTextField passwordField;
    private javax.swing.JButton signUpBttn;
    private javax.swing.JLabel usernameErrorLbl;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
